import { useState } from 'react';
import { X, Download, Copy, BookmarkPlus, RefreshCw, Check } from 'lucide-react';
import { useChatStore, type Settings } from '../../stores/chatStore';
import { usePromptAgent } from '../../hooks/usePromptAgent';
import toast from 'react-hot-toast';

interface ContextPanelProps {
  isOpen: boolean;
  onClose: () => void;
}

const ContextPanel = ({ isOpen, onClose }: ContextPanelProps) => {
  const { settings, setSettings, messages } = useChatStore();
  const { regenerate, isLoading } = usePromptAgent();
  const [copied, setCopied] = useState(false);
  const [saved, setSaved] = useState(false);

  // Get the last agent message for metadata display
  const lastAgentMessage = [...messages].reverse().find(m => m.type === 'agent' && m.response);
  const response = lastAgentMessage?.response;

  // Get the last user message for regeneration
  const lastUserMessage = [...messages].reverse().find(m => m.type === 'user');

  const handleSettingChange = (key: keyof Settings, value: string) => {
    setSettings({ [key]: value } as Partial<Settings>);
  };

  // Export as Markdown
  const handleExport = () => {
    if (!response?.optimized_prompt) return;

    const markdown = `# Optimized Prompt

## Original Request
${lastUserMessage?.content || 'N/A'}

## Optimized Prompt
${response.optimized_prompt}

## Metadata
- **Domain**: ${response.domain || 'General'}
- **Quality Score**: ${response.quality_score}/100
- **Task Type**: ${response.task_type || 'N/A'}
- **Target AI**: ${settings.target_ai}
- **Expertise Level**: ${settings.expertise_level}

## Suggestions
${response.suggestions?.map(s => `- ${s}`).join('\n') || 'No suggestions'}

---
*Generated by LUKTHAN AI Prompt Agent*
*${new Date().toLocaleString()}*
`;

    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `prompt-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast.success('Exported as Markdown');
  };

  // Copy to Clipboard
  const handleCopy = async () => {
    if (!response?.optimized_prompt) return;

    try {
      await navigator.clipboard.writeText(response.optimized_prompt);
      setCopied(true);
      toast.success('Copied to clipboard');
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      toast.error('Failed to copy');
    }
  };

  // Save to Library (localStorage for now)
  const handleSave = () => {
    if (!response?.optimized_prompt) return;

    const savedPrompts = JSON.parse(localStorage.getItem('lukthan_saved_prompts') || '[]');
    const newEntry = {
      id: Date.now(),
      original: lastUserMessage?.content || '',
      optimized: response.optimized_prompt,
      domain: response.domain,
      quality_score: response.quality_score,
      target_ai: settings.target_ai,
      created_at: new Date().toISOString()
    };
    savedPrompts.unshift(newEntry);
    localStorage.setItem('lukthan_saved_prompts', JSON.stringify(savedPrompts.slice(0, 50))); // Keep last 50

    setSaved(true);
    toast.success('Saved to library');
    setTimeout(() => setSaved(false), 2000);
  };

  // Regenerate Prompt
  const handleRegenerate = () => {
    if (!lastUserMessage) return;
    regenerate();
  };

  if (!isOpen) return null;

  return (
    <aside className="w-80 bg-bg-secondary border-l border-border-subtle flex flex-col h-full animate-slide-in-right">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-border-subtle">
        <h2 className="font-semibold text-text-primary">Configuration</h2>
        <button
          onClick={onClose}
          className="p-1.5 rounded-lg hover:bg-bg-hover transition-colors text-text-muted hover:text-text-primary"
        >
          <X className="w-4 h-4" />
        </button>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-4 space-y-6">
        {/* Settings Section */}
        <div className="space-y-4">
          {/* Target AI */}
          <div>
            <label className="block text-xs font-medium text-text-secondary uppercase tracking-wider mb-2">
              Target AI Model
            </label>
            <select
              value={settings.target_ai}
              onChange={(e) => handleSettingChange('target_ai', e.target.value)}
              className="w-full bg-bg-tertiary border border-border-subtle rounded-lg px-3 py-2.5 text-text-primary text-sm focus:border-accent focus:ring-1 focus:ring-accent transition-colors"
            >
              <optgroup label="OpenAI">
                <option value="ChatGPT (GPT-4)">ChatGPT (GPT-4)</option>
                <option value="ChatGPT (GPT-3.5)">ChatGPT (GPT-3.5)</option>
              </optgroup>
              <optgroup label="Anthropic">
                <option value="Claude">Claude (Sonnet)</option>
                <option value="Claude (Opus)">Claude (Opus)</option>
              </optgroup>
              <optgroup label="Google">
                <option value="Gemini">Gemini</option>
                <option value="Gemini Pro">Gemini Pro</option>
              </optgroup>
              <optgroup label="Open Source">
                <option value="Llama">Llama</option>
                <option value="Mistral">Mistral</option>
              </optgroup>
              <optgroup label="Code Assistants">
                <option value="Copilot">GitHub Copilot</option>
              </optgroup>
            </select>
          </div>

          {/* Expertise Level */}
          <div>
            <label className="block text-xs font-medium text-text-secondary uppercase tracking-wider mb-2">
              Expertise Level
            </label>
            <div className="grid grid-cols-2 gap-2">
              {(['Beginner', 'Intermediate', 'Professional', 'Expert'] as const).map((level) => (
                <button
                  key={level}
                  onClick={() => setSettings({ expertise_level: level })}
                  className={`px-3 py-2 text-sm font-medium rounded-lg border transition-all ${
                    settings.expertise_level === level
                      ? 'bg-accent-subtle border-accent text-accent'
                      : 'bg-bg-tertiary border-border-subtle text-text-secondary hover:bg-bg-hover hover:text-text-primary'
                  }`}
                >
                  {level}
                </button>
              ))}
            </div>
          </div>

          {/* Domain */}
          <div>
            <label className="block text-xs font-medium text-text-secondary uppercase tracking-wider mb-2">
              Domain
            </label>
            <select
              value={settings.domain}
              onChange={(e) => handleSettingChange('domain', e.target.value as Settings['domain'])}
              className="w-full bg-bg-tertiary border border-border-subtle rounded-lg px-3 py-2.5 text-text-primary text-sm focus:border-accent focus:ring-1 focus:ring-accent transition-colors"
            >
              <option value="auto">Auto Detect</option>
              <option value="coding">Coding</option>
              <option value="data_science">Data Science</option>
              <option value="research">Research</option>
              <option value="general">General</option>
            </select>
          </div>

          {/* Output Language */}
          <div>
            <label className="block text-xs font-medium text-text-secondary uppercase tracking-wider mb-2">
              Output Language
            </label>
            <select
              value={settings.language}
              onChange={(e) => handleSettingChange('language', e.target.value)}
              className="w-full bg-bg-tertiary border border-border-subtle rounded-lg px-3 py-2.5 text-text-primary text-sm focus:border-accent focus:ring-1 focus:ring-accent transition-colors"
            >
              <option value="English">English</option>
              <option value="French">French</option>
              <option value="Spanish">Spanish</option>
              <option value="German">German</option>
              <option value="Chinese">Chinese</option>
              <option value="Japanese">Japanese</option>
              <option value="Portuguese">Portuguese</option>
            </select>
          </div>
        </div>

        {/* Metadata Section - Only show if there's a response */}
        {response && (
          <div className="pt-4 border-t border-border-subtle space-y-4">
            <h3 className="text-xs font-medium text-text-secondary uppercase tracking-wider">
              Current Prompt Metadata
            </h3>

            {/* Quality Score */}
            <div>
              <div className="flex items-center justify-between mb-1.5">
                <span className="text-sm text-text-secondary">Quality Score</span>
                <span className="text-sm font-medium text-text-primary">
                  {response.quality_score}/100
                </span>
              </div>
              <div className="progress-bar">
                <div
                  className="progress-bar-fill"
                  style={{ width: `${response.quality_score}%` }}
                />
              </div>
            </div>

            {/* Intent */}
            <div>
              <span className="text-sm text-text-secondary">Detected Intent</span>
              <div className="mt-1">
                <span className="badge badge-accent">
                  {response.intent?.replace('_', ' ')}
                </span>
              </div>
            </div>

            {/* Domain */}
            <div>
              <span className="text-sm text-text-secondary">Domain</span>
              <div className="mt-1">
                <span className="badge">
                  {response.domain?.replace('_', ' ')}
                </span>
              </div>
            </div>

            {/* Key Topics */}
            {response.metadata?.key_topics && response.metadata.key_topics.length > 0 && (
              <div>
                <span className="text-sm text-text-secondary">Key Topics</span>
                <div className="mt-1.5 flex flex-wrap gap-1.5">
                  {response.metadata.key_topics.map((topic, i) => (
                    <span key={i} className="badge text-xs">
                      {topic}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {/* Complexity */}
            {response.metadata?.complexity && (
              <div className="flex items-center justify-between">
                <span className="text-sm text-text-secondary">Complexity</span>
                <span className="text-sm text-text-primary capitalize">
                  {response.metadata.complexity}
                </span>
              </div>
            )}
          </div>
        )}

        {/* Actions Section */}
        <div className="pt-4 border-t border-border-subtle space-y-2">
          <h3 className="text-xs font-medium text-text-secondary uppercase tracking-wider mb-3">
            Actions
          </h3>

          <button
            onClick={handleExport}
            className="btn btn-secondary w-full justify-start"
            disabled={!response?.optimized_prompt}
          >
            <Download className="w-4 h-4" />
            Export as Markdown
          </button>

          <button
            onClick={handleCopy}
            className="btn btn-secondary w-full justify-start"
            disabled={!response?.optimized_prompt}
          >
            {copied ? <Check className="w-4 h-4 text-success" /> : <Copy className="w-4 h-4" />}
            {copied ? 'Copied!' : 'Copy to Clipboard'}
          </button>

          <button
            onClick={handleSave}
            className="btn btn-secondary w-full justify-start"
            disabled={!response?.optimized_prompt}
          >
            {saved ? <Check className="w-4 h-4 text-success" /> : <BookmarkPlus className="w-4 h-4" />}
            {saved ? 'Saved!' : 'Save to Library'}
          </button>

          <button
            onClick={handleRegenerate}
            className="btn btn-ghost w-full justify-start text-text-muted"
            disabled={!response?.optimized_prompt || isLoading}
          >
            <RefreshCw className={`w-4 h-4 ${isLoading ? 'animate-spin' : ''}`} />
            {isLoading ? 'Regenerating...' : 'Regenerate Prompt'}
          </button>
        </div>
      </div>
    </aside>
  );
};

export default ContextPanel;
